name: CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [12, 14, 16, 18]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: Set git config
      run: git config --global url."https://github.com/".insteadOf ssh://git@github.com/
    - run: npm ci
    - run: npm test
